INSERT INTO Products
(Name, 
 Category, 
 Description, 
 Quantity, 
 Price, 
 Image
)
VALUES
('Dell XPS 13', 
 1, 
 'A high-performance laptop with an Intel Core i7 processor, 16GB RAM, and a 512GB SSD.', 
 1, 
 1499, 
 'https://i.dell.com/is/image/DellContent//content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/13-9370/global-spi/notebook-xps-13-9370-campaign-hero-504x350-ng.psd?fmt=jpg'
),
('HP Spectre x360', 
 1, 
 'A versatile 2-in-1 laptop with an Intel Core i5 processor, 8GB RAM, and a 256GB SSD.', 
 3, 
 1199, 
 'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c06924582.png'
),
('Lenovo ThinkPad X1 Carbon', 
 1, 
 'A lightweight and durable business laptop with an Intel Core i7 processor, 16GB RAM, and a 512GB SSD.', 
 2, 
 1799, 
 'https://www.lenovo.com/medias/feature-1-lenovo-thinkpad-x1-carbon-5.png?context=bWFzdGVyfHJvb3R8MTc0NTk3fGltYWdlL3BuZ3xoNzgvaDQ0LzkzNjU3OTM2MzYzODIucG5nfGNjZGFmNjI3ODU4NWU1OGVhNjZlYWYwODRkYmE5YmZiNmEyODQ5NTYyZDk3NTlkZDgzOWVhM2FjNDFmMjg1M2Q'
),
('ASUS ROG Zephyrus G14', 
 1, 
 'A gaming laptop with an AMD Ryzen 9 processor, 16GB RAM, and a 1TB SSD.', 
 4, 
 1999, 
 'https://rog.asus.com/media/1578096205427.webp'
),
('Acer Swift 3', 
 1, 
 'A budget-friendly laptop with an AMD Ryzen 5 processor, 8GB RAM, and a 512GB SSD.', 
 5, 
 699, 
 'https://images.acer.com/is/image/acer/acer-swift-3-sf314-512-sf-314-512t-fingerprint-backlit-on-wallpaper-pure-silver-01-1?$Product-Cards-XL$'
),
('Apple MacBook Pro', 
 1, 
 'A high-end laptop with an Intel Core i9 processor, 32GB RAM, and a 1TB SSD.', 
 1, 
 2799, 
 'https://www.apple.com/newsroom/images/product/mac/standard/Apple_MacBook-Pro_14-16-inch_10182021_big.jpg.slideshow-xlarge_2x.jpg'
),
('Microsoft Surface Laptop 3', 
 1, 
 'A sleek and powerful laptop with an Intel Core i7 processor, 16GB RAM, and a 512GB SSD.', 
 3, 
 1499, 
 'https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE3oT8Y?ver=1a35&q=90&m=6&h=705&w=1253&b=%23FFFFFFFF&f=jpg&o=f&p=140&aim=true'
),
('Razer Blade 15', 
 1, 
 'A premium gaming laptop with an Intel Core i7 processor, 16GB RAM, and a 512GB SSD.', 
 2, 
 1799, 
 'https://bbpcdn.pstatic.gr/bpimg31/3ymyH/1NEVTe_SX939Y492/1649928948/razer-blade-15.jpg'
),
('LG Gram 17', 
 1, 
 'A lightweight and long-lasting laptop with an Intel Core i7 processor, 16GB RAM, and a 1TB SSD.', 
 2, 
 1699, 
 'https://www.lg.com/us/images/laptops/md06060196/gallery/D-001.jpg'
),
('HP Envy x360', 
 1, 
 'A versatile 2-in-1 laptop with an AMD Ryzen 7 processor, 16GB RAM, and a 512GB SSD.', 
 4, 
 1299, 
 'https://www.hp.com/content/dam/sites/worldwide/personal-computers/consumer/laptops-and-2-n-1s/envy/get-a-fresh-perspective_v2.png'
),
('MSI GF63', 
 1, 
 'A budget-friendly gaming laptop with an Intel Core i5 processor, 8GB RAM, and a 512GB SSD.', 
 6, 
 899, 
 'https://storage-asset.msi.com/global/picture/image/feature/nb/GF/Thin-GF63-12HW/images/GF63-NB.png'
),
('Dell Inspiron 15 3000', 
 1, 
 'A basic laptop with an Intel Celeron processor, 4GB RAM, and a 128GB SSD.', 
 10, 
 399, 
 'https://i.dell.com/is/image/DellContent//content/dam/ss2/product-images/dell-client-products/notebooks/inspiron-notebooks/inspiron-3502/pdp/notebook_laptop_inspiron_bk_3502_pdp_gallery.jpg?fmt=jpg&wid=570&hei=400'
),
('Lenovo Yoga C940', 
 1, 
 'A versatile 2-in-1 laptop with an Intel Core i7 processor, 16GB RAM, and a 512GB SSD.', 
 3, 
 1599, 
 'https://static.lenovo.com/na/subseries/hero/lenovo-laptop-yoga-c940-hero-15-3yr-support.png'
),
('Acer Predator Triton 500', 
 1, 
 'A high-performance gaming laptop with an Intel Core i7 processor, 16GB RAM, and a 512GB SSD.', 
 2, 
 1999, 
 'https://images.acer.com/is/image/acer/predator-triton-500-se-pt516-52s-fingerprint-3zone-backlit-on-wallpaper-steel-gray-01-1?$Product-Cards-XL$'
),
('HP Pavilion x360', 
 1, 
 'A 2-in-1 laptop with an Intel Core i5 processor, 8GB RAM, and a 512GB SSD.', 
 7, 
 899, 
 'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c07050346.png'
);