INSERT INTO Products
(Name, 
 Category, 
 Description, 
 Quantity, 
 Price, 
 Image
)
VALUES
('iPhone 13', 
 3, 
 'The latest flagship smartphone from Apple, featuring an A15 Bionic chip, improved cameras, and a sleek design.', 
 500, 
 799.00, 
 'https://example.com/iphone13.jpg'
),
('Samsung Galaxy S21', 
 3, 
 'A high-end Android smartphone from Samsung with a powerful processor, advanced camera system, and 5G connectivity.', 
 600, 
 799.00, 
 'https://example.com/samsungs21.jpg'
),
('Google Pixel 6', 
 3, 
 'Google''s latest flagship smartphone featuring an advanced camera system, powerful processor, and the latest version of Android.', 
 300, 
 599.00, 
 'https://example.com/pixel6.jpg'
),
('OnePlus 9', 
 3, 
 'A high-performance Android smartphone with a fast-charging battery, a powerful processor, and a high-refresh-rate display.', 
 400, 
 729.00, 
 'https://example.com/oneplus9.jpg'
),
('Xiaomi Mi 11', 
 3, 
 'A powerful and feature-packed smartphone from Xiaomi with a high-quality display, a fast-charging battery, and a versatile camera system.', 
 350, 
 749.00, 
 'https://example.com/xiaomimi11.jpg'
),
('Oppo Find X3 Pro', 
 3, 
 'A high-end Android smartphone with a premium design, a powerful processor, and a unique camera system that can capture microscopic images.', 
 200, 
 1199.00, 
 'https://example.com/oppofindx3pro.jpg'
),
('Sony Xperia 1 III', 
 3, 
 'Sony''s latest flagship smartphone featuring a 4K OLED display, a high-quality camera system, and a fast-charging battery.', 
 150, 
 1299.00, 
 'https://example.com/sonyxperia1iii.jpg'
),
('LG Wing', 
 3, 
 'A unique smartphone with a rotating screen that reveals a secondary display underneath, perfect for multitasking and gaming.', 
 250, 
 999.00, 
 'https://example.com/lgwing.jpg'
),
('Motorola Moto G Stylus 5G', 
 3, 
 'An affordable Android smartphone with a stylus, 5G connectivity, and a large display.', 
 700, 
 399.00, 
 'https://example.com/motogstylus5g.jpg'
),
('Asus ROG Phone 5', 
 3, 
 'A gaming-focused smartphone with a powerful processor, a high-refresh-rate display, and a large battery.', 
 200, 
 999.00, 
 'https://example.com/asusrogphone5.jpg'
),
('ZTE Axon 30 Ultra', 
 3, 
 'A feature-packed Android smartphone with a high-quality camera system, a fast-charging battery, and 5G connectivity.', 
 350, 
 749.00, 
 'https://example.com/zteaxon30ultra.jpg'
),
('Vivo X60 Pro', 
 3, 
 'A high-performance smartphone with a premium design, a powerful camera system, and advanced camera features.', 
 300, 
 749.00, 
 'https://example.com/vivox60pro.jpg'
),
('Realme GT', 
 3, 
 'A budget-friendly smartphone with a powerful processor, a high-refresh-rate display, and a premium design.', 
 500, 
 499.00, 
 'https://example.com/realmegt.jpg'
),
('Nokia X20', 
 3, 
 'An affordable Android smartphone with a large display, 5G connectivity, and a long-lasting battery.', 
 400, 
 349.00, 
 'https://example.com/nokiax20.jpg'
),
('BlackBerry Key2', 
 3, 
 'A unique smartphone with a physical keyboard, perfect for users who prefer a tactile typing experience.', 
 100, 
 699.00, 
 'https://example.com/blackberrykey2.jpg'
),
('HTC U12 Plus', 
 3, 
 'A high-end Android smartphone with a premium design, a fast-charging battery, and a dual-camera system.', 
 50, 
 699.00, 
 'https://example.com/htcu12plus.jpg'
);