INSERT INTO Products
(Name, 
 Category, 
 Description, 
 Quantity, 
 Price, 
 Image
)
VALUES
('iPad Pro', 
 2, 
 'A high-end tablet from Apple with a powerful M1 chip, a Liquid Retina XDR display, and 5G connectivity.', 
 300, 
 799.00, 
 'https://example.com/ipadpro.jpg'
),
('Samsung Galaxy Tab S7+', 
 2, 
 'A premium Android tablet with a large AMOLED display, a powerful processor, and 5G connectivity.', 
 250, 
 849.99, 
 'https://example.com/samsungtabs7plus.jpg'
),
('Microsoft Surface Pro 7', 
 2, 
 'A versatile 2-in-1 tablet with a detachable keyboard, a high-quality display, and a powerful processor.', 
 200, 
 899.99, 
 'https://example.com/surfacepro7.jpg'
),
('Google Pixel Slate', 
 2, 
 'A high-end tablet with a premium design, a high-quality display, and the latest version of Chrome OS.', 
 150, 
 799.99, 
 'https://example.com/pixelslate.jpg'
),
('Amazon Fire HD 10', 
 2, 
 'An affordable tablet with a large display, Alexa integration, and access to the Amazon Appstore.', 
 500, 
 149.99, 
 'https://example.com/firehd10.jpg'
),
('Lenovo Tab P11 Pro', 
 2, 
 'A sleek and powerful Android tablet with a premium design, a high-quality display, and a long-lasting battery.', 
 300, 
 499.99, 
 'https://example.com/lenovotabp11pro.jpg'
),
('Huawei MatePad Pro', 
 2, 
 'A high-end Android tablet with a large display, a powerful processor, and a sleek design.', 
 150, 
 699.99, 
 'https://example.com/huaweimatepadpro.jpg'
),
('ASUS ZenPad S8.0', 
 2, 
 'An affordable Android tablet with a high-quality display, a fast-charging battery, and a premium design.', 
 400, 
 199.99, 
 'https://example.com/asuszenpads8.jpg'
),
('Sony Xperia Tablet Z4', 
 2, 
 'A high-end tablet with a slim and waterproof design, a high-quality display, and a powerful processor.', 
 100, 
 699.99, 
 'https://example.com/sonyxperiatabletz4.jpg'
),
('LG G Pad 5', 
 2, 
 'A mid-range Android tablet with a large display, a long-lasting battery, and a premium design.', 
 200, 
 299.99, 
 'https://example.com/lggpad5.jpg'
),
('Lenovo Yoga Smart Tab', 
 2, 
 'A versatile Android tablet with a built-in kickstand, a high-quality display, and Google Assistant integration.', 
 250, 
 349.99, 
 'https://example.com/lenovoyogasmarttab.jpg'
),
('Samsung Galaxy Tab A7 Lite', 
 2, 
 'An affordable Android tablet with a compact design, a long-lasting battery, and a high-quality display.', 
 600, 
 149.99, 
 'https://example.com/samsungtaba7lite.jpg'
),
('Apple iPad (9th generation)', 
 2, 
 'The latest entry-level iPad from Apple with a powerful A13 Bionic chip, a Retina display, and support for the Apple Pencil.', 
 400, 
 329.00, 
 'https://example.com/ipad9thgen.jpg'
),
('Google Nexus 9', 
 2, 
 'A mid-range Android tablet with a high-quality display and access to the Google Play Store.', 
 50, 
 299.99, 
 'https://example.com/googlenexus9.jpg'
),
('Amazon Fire HD 8', 
 2, 
 'An affordable tablet with a compact design, Alexa integration, and access to the Amazon Appstore.', 
 800, 
 89.99, 
 'https://example.com/firehd8.jpg'
);